### ISSUE TITLE
Nome repository errato

### ISSUE THREAD

**Issue by Pastello** [KatharaFramework/Netkit-Lab-Generator#1]
Ciao ragazzi, credo che questa applicazione possa lanciare solo lab Kathara' ormai (perché Netkit e Kathara' hanno la variabile NETKIT_HOME settata diversamente e questa app tiene conto del settaggio di Kathara'), quindi vi volevo suggerire di cambiare il nome della repository.

P.S. A parte questo, io per la mia tesi ho fatto alcune modifiche per aggiungere switch e controller per OpenFlow. Posso aprire una pull request?

**Comment by Kidel** [comment]
Di fatto è solo la funzione "Run on Host" che necessita quella variabile. Tutte le altre sono compatibili con netkit. Il nome è sostanzialmente storico, ma in futuro potremmo pensare di cambiarlo. 

Riguardo alla tua PR, certo!
E grazie mille per il contributo. 

Sarà utilissimo per gli studenti che quest'anno dovranno fare switch OpenFlow per l'esame. 

Ti segnalo che sulla repo Katharà abbiamo implementato un fix un paio di giorni fa che permette alle network Docker di comportarsi da hub. Questo permette la creazione di switch OpenFlow di livello 2.
