### ISSUE TITLE
Cannot handle added machines because this doesn't scroll

### ISSUE THREAD

**Issue by north-country** [KatharaFramework/Netkit-Lab-Generator#33]
I cannot operate the added machines because the screen does not scroll.
There is no vertical scrollbar on the screen, and using the mouse wheel does not work either.
I tried clicking on the machines in the overview window, but this did not change the screen either.
![image](https://github.com/KatharaFramework/Netkit-Lab-Generator/assets/35770699/def25345-4666-4459-8a23-6ee6b1135730)

**Comment by nguyenluminhvy** [comment]
same issue

**Comment by nguyenluminhvy** [comment]
I found useful PR https://github.com/KatharaFramework/Netkit-Lab-Generator/pull/34

**Comment by lorenzo93** [comment]
Hi,

The scrolling was working previously, and I'm not sure why it suddenly stopped.
I've requested some changes in PR #34, and once the author makes them, I'll release a new version.
Apologies for the inconvenience, and thank you for your patience.

**Comment by lorenzo93** [comment]
Hi,

@giovanni-grieco fixed this issue in PR #35.
The PR is already merged so I'll close this issue
